rough <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", na.strings = "?")
filtered <- subset(rough, Date == "1/2/2007"| Date == "2/2/2007")
filtered$Date.Time <- paste(filtered$Date, filtered$Time)
final <- cbind(filtered[1:2],filtered[10], filtered[3:9])
final$Date.Time <- strptime(final$Date.Time, format = "%d/%m/%Y %H:%M:%S")

png(file = "plot3.png")
plot(final$Date.Time, final$Sub_metering_1, type = "l", xlab = "", ylab = "Energy sub metering")
points(final$Date.Time, final$Sub_metering_2, type = "l", col = "red")
points(final$Date.Time, final$Sub_metering_3, type = "l", col = "blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty = c(1, 1, 1), col = c("black", "red", "blue"))
dev.off()